# -*- coding: utf-8 -*-
"""app_var.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oijTLuzP5_i-FrsPbDZybcjMu3iEKJL-
"""

# ============================================================
# APP STREAMLIT
# PÉRDIDA MÁXIMA + VaR + CVaR
# Yahoo Finance + yfinance
# ============================================================


import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np

# ============================================================
# CONFIGURACIÓN
# ============================================================

st.set_page_config(
    page_title="Gestión de Riesgo",
    page_icon="📊",
    layout="wide"
)

st.title(" Calculadora de Riesgo Financiero (RiskPulse)")

st.write(
    "Calcula Maximum Drawdown, VaR y CVaR utilizando "
    "información histórica de Yahoo Finance."
)

st.divider()

# ============================================================
# ENTRADAS
# ============================================================

col1, col2 = st.columns(2)

with col1:

    ticker = st.text_input(
        "🔎 Clave de pizarra de Yahoo Finance",
        value="AAPL",
        help="Ejemplos: AAPL, MSFT, CEMEXCPO.MX, WALMEX.MX, BTC-USD"
    )

    monto = st.number_input(
        "💰 Monto a invertir ",
        min_value=1.0,
        value=100000.0,
        step=1000.0
    )

with col2:

    periodo = st.selectbox(
        "📅 Periodo histórico",
        ["1y", "2y", "5y", "10y", "max"],
        index=2
    )

    confianza = st.selectbox(
        "🎯 Nivel de confianza",
        [0.90, 0.95, 0.99],
        index=1,
        format_func=lambda x: f"{x:.0%}"
    )

# ============================================================
# BOTÓN
# ============================================================

if st.button(
    "🚀 Calcular riesgo",
    type="primary",
    use_container_width=True
):

    ticker = ticker.strip().upper()

    if not ticker:
        st.error("Introduce una clave de pizarra.")
        st.stop()

    with st.spinner("Descargando información de Yahoo Finance..."):

        try:

            # =================================================
            # DESCARGAR DATOS
            # =================================================

            datos = yf.download(
                ticker,
                period=periodo,
                interval="1d",
                auto_adjust=True,
                progress=False
            )

            if datos.empty:
                st.error(
                    f"No se encontraron datos para {ticker}."
                )
                st.stop()

            # =================================================
            # PRECIO DE CIERRE
            # =================================================

            if isinstance(datos.columns, pd.MultiIndex):

                precios = datos["Close"].iloc[:, 0]

            else:

                precios = datos["Close"]

            precios = precios.dropna()

            if len(precios) < 30:

                st.error(
                    "No existen suficientes observaciones "
                    "para realizar el análisis."
                )

                st.stop()

            # =================================================
            # RENDIMIENTOS
            # =================================================

            rendimientos = precios.pct_change().dropna()

            # =================================================
            # MAXIMUM DRAWDOWN
            # =================================================

            maximo_acumulado = precios.cummax()

            drawdown = (
                precios / maximo_acumulado
            ) - 1

            mdd = drawdown.min()

            fecha_min = drawdown.idxmin()

            fecha_max = precios.loc[:fecha_min].idxmax()

            precio_max = precios.loc[fecha_max]

            precio_min = precios.loc[fecha_min]

            # =================================================
            # VaR HISTÓRICO
            # =================================================

            alpha = 1 - confianza

            percentil = rendimientos.quantile(alpha)

            VaR = -percentil

            # =================================================
            # CVaR HISTÓRICO
            # =================================================

            rendimientos_extremos = rendimientos[
                rendimientos <= percentil
            ]

            CVaR = -rendimientos_extremos.mean()

            # =================================================
            # PÉRDIDAS MONETARIAS
            # =================================================

            perdida_MDD = monto * abs(mdd)

            perdida_VaR = monto * VaR

            perdida_CVaR = monto * CVaR

            # =================================================
            # CAPITAL RESTANTE
            # =================================================

            capital_MDD = monto - perdida_MDD

            capital_VaR = monto - perdida_VaR

            capital_CVaR = monto - perdida_CVaR

            # =================================================
            # RESULTADOS PRINCIPALES
            # =================================================

            st.success(
                f"Análisis completado para {ticker}"
            )

            st.subheader("Principales indicadores")

            c1, c2, c3 = st.columns(3)

            with c1:

                st.metric(
                    "Maximum Drawdown",
                    f"{mdd:.2%}"
                )

                st.write(
                    f"Pérdida máxima histórica: "
                    f"**${perdida_MDD:,.2f} **"
                )

            with c2:

                st.metric(
                    f"VaR histórico ({confianza:.0%})",
                    f"{VaR:.2%}"
                )

                st.write(
                    f"Pérdida diaria estimada: "
                    f"**${perdida_VaR:,.2f}**"
                )

            with c3:

                st.metric(
                    f"CVaR histórico ({confianza:.0%})",
                    f"{CVaR:.2%}"
                )

                st.write(
                    f"Pérdida promedio extrema: "
                    f"**${perdida_CVaR:,.2f} **"
                )

            # =================================================
            # TABLA DE RESULTADOS
            # =================================================

            st.divider()

            st.subheader("Resumen del riesgo")

            resumen = pd.DataFrame({

                "Indicador": [
                    "Monto invertido",
                    "Maximum Drawdown",
                    "Pérdida por MDD",
                    f"VaR ({confianza:.0%})",
                    "Pérdida por VaR",
                    f"CVaR ({confianza:.0%})",
                    "Pérdida por CVaR",
                    "Capital después de MDD",
                    "Capital después de VaR",
                    "Capital después de CVaR"
                ],

                "Resultado": [

                    f"${monto:,.2f} ",

                    f"{mdd:.2%}",

                    f"${perdida_MDD:,.2f} ",

                    f"{VaR:.2%}",

                    f"${perdida_VaR:,.2f} ",

                    f"{CVaR:.2%}",

                    f"${perdida_CVaR:,.2f} ",

                    f"${capital_MDD:,.2f} ",

                    f"${capital_VaR:,.2f} ",

                    f"${capital_CVaR:,.2f} "
                ]
            })

            st.dataframe(
                resumen,
                use_container_width=True,
                hide_index=True
            )

            # =================================================
            # GRÁFICA DE PRECIO
            # =================================================

            st.divider()

            st.subheader("Precio histórico")

            st.line_chart(precios)

            # =================================================
            # GRÁFICA DE DRAWDOWN
            # =================================================

            st.subheader("Drawdown histórico")

            st.line_chart(drawdown)

            # =================================================
            # DISTRIBUCIÓN DE RENDIMIENTOS
            # =================================================

            st.subheader("Distribución de rendimientos")

            st.bar_chart(
                rendimientos
            )

            # =================================================
            # INTERPRETACIÓN
            # =================================================

            st.divider()

            st.subheader("Interpretación")

            st.write(
                f"""
                Para una inversión de **${monto:,.2f} MXN** en **{ticker}**:

                - El **Maximum Drawdown** histórico fue de
                **{abs(mdd):.2%}**.

                - Con un nivel de confianza de
                **{confianza:.0%}**, el **VaR histórico diario**
                es de **{VaR:.2%}**, equivalente a
                **${perdida_VaR:,.2f} **.

                - El **CVaR** es de **{CVaR:.2%}**, lo que significa
                que, considerando únicamente los peores días
                incluidos en el VaR, la pérdida promedio fue de
                aproximadamente **${perdida_CVaR:,.2f} **.
                """
            )

            # =================================================
            # ADVERTENCIA
            # =================================================

            st.warning(
                "VaR, CVaR y Maximum Drawdown son medidas basadas "
                "en información histórica. No representan una "
                "garantía ni una predicción de pérdidas futuras."
            )

        except Exception as e:

            st.error(
                f"Ocurrió un error: {e}"
            )
